# Generated by Django 6.0.3 on 2026-07-08 08:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('phone3', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('family_size', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='beneficiaries/')),
                ('category', models.CharField(choices=[('poor', 'Poor People'), ('staff', 'Staff Member'), ('student', 'Madrassat Student'), ('teacher', 'Oustadh'), ('elder', 'Elder'), ('orphan', 'Orphan kid'), ('sick', 'Sick Person'), ('disabled', 'Disabled Person'), ('widow', 'Widow'), ('refugee', 'Refugee'), ('family', 'Family member of a beneficiary'), ('family', 'Family member of staff'), ('other', 'Other')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_needed_person', models.BooleanField(default=False)),
                ('is_serious', models.BooleanField(default=False)),
                ('is_muslim', models.BooleanField(default=True)),
                ('participated_programs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-update_at'],
                'permissions': [('can_verify_beneficiary', 'Can verify beneficiary records'), ('can_mark_serious', 'Can mark beneficiary as serious'), ('can_mark_muslim', 'Can mark beneficiary as muslim')],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='program.beneficiary')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beneficiary Verification',
                'verbose_name_plural': 'Beneficiary Verifications',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_verification', 'Can approve beneficiary verifications'), ('can_reject_verification', 'Can reject beneficiary verifications')],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program_type', models.CharField(choices=[('zakaat', 'Zakaat Distribution'), ('food_pack', 'Food Pack Distribution'), ('iftar', 'Iftar Distribution'), ('sadaqah', 'Sadaqah'), ('clothing', 'Clothing Distribution'), ('school_supplies', 'School Supplies Distribution'), ('medical', 'Medical Assistance'), ('sponsorship', 'Sponsorship Program'), ('training', 'Training/Workshop'), ('hot meal', 'Hot Meal Distribution'), ('dawrah', 'Dawrah'), ('qurbani', 'Qurbani'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('beneficiaries', models.ManyToManyField(blank=True, related_name='programs', to='program.beneficiary')),
            ],
            options={
                'ordering': ['-created_at', '-update_at'],
                'permissions': [('can_publish_program', 'Can publish programs'), ('can_view_program_stats', 'Can view program statistics')],
            },
        ),
        migrations.CreateModel(
            name='ProgramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'program')},
            },
        ),
        migrations.CreateModel(
            name='ProgramShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'program')},
            },
        ),
    ]
