# Generated by Django 6.0.3 on 2026-03-24 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('phone3', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('family_size', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='beneficiaries/')),
                ('category', models.CharField(choices=[('poor', 'Poor People'), ('staff', 'Staff Member'), ('student', 'Madrassat Student'), ('teacher', 'Oustadh'), ('elder', 'Elder'), ('orphan', 'Orphan kid'), ('sick', 'Sick Person'), ('disabled', 'Disabled Person'), ('widow', 'Widow'), ('refugee', 'Refugee'), ('family', 'Family member of a beneficiary'), ('family', 'Family member of staff'), ('other', 'Other')], max_length=20)),
                ('is_needed_person', models.BooleanField(default=False)),
                ('is_serious', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program_type', models.CharField(choices=[('zakaat', 'Zakaat Distribution'), ('food_pack', 'Food Pack Distribution'), ('iftar', 'Iftar Distribution'), ('sadaqah', 'Sadaqah'), ('clothing', 'Clothing Distribution'), ('school_supplies', 'School Supplies Distribution'), ('medical', 'Medical Assistance'), ('sponsorship', 'Sponsorship Program'), ('training', 'Training/Workshop'), ('hot meal', 'Hot Meal Distribution'), ('dawrah', 'Dawrah'), ('qurbani', 'Qurbani'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiaries', models.ManyToManyField(blank=True, related_name='programs', to='program.beneficiary')),
            ],
        ),
    ]
