# Generated by Django 5.2.4 on 2026-10-02 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('phone3', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('village', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('family_size', models.PositiveIntegerField(default=1)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='beneficiaries/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='beneficiaries/id_documents/')),
                ('category', models.CharField(choices=[('poor', 'Poor People'), ('staff', 'Staff Member'), ('student', 'Madrassat Student'), ('teacher', 'Oustadh'), ('elder', 'Elder'), ('orphan', 'Orphan'), ('sick', 'Sick Person'), ('disabled', 'Disabled Person'), ('widow', 'Widow'), ('refugee', 'Refugee'), ('family_beneficiary', 'Family Member of Beneficiary'), ('family_staff', 'Family Member of Staff'), ('other', 'Other')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_needed_person', models.BooleanField(default=False)),
                ('is_serious', models.BooleanField(default=False)),
                ('is_muslim', models.BooleanField(default=True)),
                ('participated_programs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-update_at'],
                'permissions': [('can_verify_beneficiary', 'Can verify beneficiary records'), ('can_mark_serious', 'Can mark beneficiary as serious'), ('can_mark_muslim', 'Can mark beneficiary as muslim')],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='program.beneficiary')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beneficiary Verification',
                'verbose_name_plural': 'Beneficiary Verifications',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_verification', 'Can approve beneficiary verifications'), ('can_reject_verification', 'Can reject beneficiary verifications')],
            },
        ),
        migrations.CreateModel(
            name='DisabledBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_type', models.CharField(max_length=100)),
                ('disability_percentage', models.PositiveIntegerField()),
                ('uses_wheelchair', models.BooleanField(default=False)),
                ('needs_assistant', models.BooleanField(default=False)),
                ('can_work', models.BooleanField(default=True)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disability_profile', to='program.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='ElderBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lives_alone', models.BooleanField(default=False)),
                ('mobility_problem', models.BooleanField(default=False)),
                ('chronic_disease', models.BooleanField(default=False)),
                ('caregiver_name', models.CharField(blank=True, max_length=255)),
                ('receives_pension', models.BooleanField(default=False)),
                ('pension_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elder_profile', to='program.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=100)),
                ('dependent', models.BooleanField(default=True)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_profile', to='program.beneficiary')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='OrphanBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_alive', models.BooleanField(default=False)),
                ('mother_alive', models.BooleanField(default=True)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=255)),
                ('sponsor', models.CharField(blank=True, max_length=255)),
                ('receives_monthly_support', models.BooleanField(default=False)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orphan_profile', to='program.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='PoorBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(max_length=100)),
                ('income_source', models.CharField(max_length=150)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('house_type', models.CharField(max_length=100)),
                ('house_owner', models.BooleanField(default=False)),
                ('receives_government_help', models.BooleanField(default=False)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('has_food_shortage', models.BooleanField(default=False)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('priority_score', models.PositiveIntegerField(default=0)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poor_profile', to='program.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program_type', models.CharField(choices=[('zakaat', 'Zakaat Distribution'), ('food_pack', 'Food Pack Distribution'), ('iftar', 'Iftar Distribution'), ('sadaqah', 'Sadaqah'), ('clothing', 'Clothing Distribution'), ('school_supplies', 'School Supplies Distribution'), ('medical', 'Medical Assistance'), ('sponsorship', 'Sponsorship Program'), ('training', 'Training/Workshop'), ('hot meal', 'Hot Meal Distribution'), ('dawrah', 'Dawrah'), ('qurbani', 'Qurbani'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('beneficiaries', models.ManyToManyField(blank=True, related_name='programs', to='program.beneficiary')),
            ],
            options={
                'ordering': ['-created_at', '-update_at'],
                'permissions': [('can_publish_program', 'Can publish programs'), ('can_view_program_stats', 'Can view program statistics')],
            },
        ),
        migrations.CreateModel(
            name='ProgramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefugeeBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin', models.CharField(max_length=100)),
                ('refugee_card_number', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('refugee_camp', models.CharField(max_length=255)),
                ('has_permanent_home', models.BooleanField(default=False)),
                ('employment_status', models.CharField(max_length=100)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refugee_profile', to='program.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='SickBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
                ('doctor', models.CharField(max_length=255)),
                ('treatment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('needs_surgery', models.BooleanField(default=False)),
                ('chronic', models.BooleanField(default=False)),
                ('disability_caused', models.BooleanField(default=False)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='program.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='StaffBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('employment_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='program.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madrassa_name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=100)),
                ('memorized_juz', models.PositiveIntegerField(default=0)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('school_grade', models.CharField(blank=True, max_length=100)),
                ('orphan', models.BooleanField(default=False)),
                ('sponsor_name', models.CharField(blank=True, max_length=255)),
                ('boarding', models.BooleanField(default=False)),
                ('attendance_percentage', models.PositiveIntegerField(default=100)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='program.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=200)),
                ('teaches_quran', models.BooleanField(default=True)),
                ('monthly_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='program.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='WidowBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_date_of_death', models.DateField()),
                ('children', models.PositiveIntegerField(default=0)),
                ('employed', models.BooleanField(default=False)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receives_support', models.BooleanField(default=False)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widow_profile', to='program.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'program')},
            },
        ),
        migrations.CreateModel(
            name='ProgramShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'program')},
            },
        ),
    ]
