# Generated by Django 6.0.3 on 2026-03-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ['-created_at', '-update_at']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-created_at', '-update_at']},
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='program',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
