# Generated by Django 6.0.3 on 2026-03-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_beneficiary_options_alter_program_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
